// Mocks generated by Mockito 5.4.5 from annotations
// in exam_app/test/feature/exam/api/datasource_impl/exam_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:exam_app/feature/exam/api/client/exam_api_client.dart' as _i4;
import 'package:exam_app/feature/exam/data/models/check_question_response.dart'
    as _i3;
import 'package:exam_app/feature/exam/data/models/question_response.dart'
    as _i2;
import 'package:exam_app/feature/exam/data/models/requests/check_question_request.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuestionResponse_0 extends _i1.SmartFake
    implements _i2.QuestionResponse {
  _FakeQuestionResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckQuestionResponse_1 extends _i1.SmartFake
    implements _i3.CheckQuestionResponse {
  _FakeCheckQuestionResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExamApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamApiClient extends _i1.Mock implements _i4.ExamApiClient {
  MockExamApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.QuestionResponse> getQuestion(String? examId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestion,
          [examId],
        ),
        returnValue:
            _i5.Future<_i2.QuestionResponse>.value(_FakeQuestionResponse_0(
          this,
          Invocation.method(
            #getQuestion,
            [examId],
          ),
        )),
      ) as _i5.Future<_i2.QuestionResponse>);

  @override
  _i5.Future<_i3.CheckQuestionResponse> checkQuestion(
          _i6.CheckQuestionRequest? checkQuestionRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkQuestion,
          [checkQuestionRequest],
        ),
        returnValue: _i5.Future<_i3.CheckQuestionResponse>.value(
            _FakeCheckQuestionResponse_1(
          this,
          Invocation.method(
            #checkQuestion,
            [checkQuestionRequest],
          ),
        )),
      ) as _i5.Future<_i3.CheckQuestionResponse>);
}
